-- vim: foldmarker=(((,))):foldmethod=marker:foldlevel=0:shiftwidth=2:softtabstop=2:tabstop=2

require("user.options")
require("user.autocommands")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp") -- 'lsp' is a folder with detailed config with an entry-point file 'init.lua'
require("user.telescope")
require("user.treesitter")
require("user.asynctasks_asyncrun")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
-- require("user.alpha")
require("user.whichkey")
require("user.stabilize")
require("user.todo_comments")
require("user.filetype")
require("user.neoscroll")
require("user.hlslens")
require("user.pqf")
require("user.treesitter_context")
require("user.zen_mode")
require("user.twilight")
require("user.iswap")
require("user.lightbulb")
require("user.trouble")
require("user.lsp_signature")
require("user.aerial")
require("user.goto_preview")
